#!/usr/bin/python

import os

scripts = [
    ["pt-summary", "http://percona.com/get/pt-summary"],
]

for s in scripts:
    cmd = "wget -N -o %s '%s'" % (s[0], s[1])
    print(cmd)
    os.system(cmd)
