#!/bin/bash

scripts=(
    "pt-summary" "http://percona.com/get/pt-summary"
    "get-pip.py" "https://bootstrap.pypa.io/get-pip.py"
    "redis-faina.py" "https://raw.githubusercontent.com/facebookarchive/redis-faina/master/redis-faina.py"
)

DL="wget -Nq "
[[ -n $1 ]] && PROXY=$1

set -e

for (( i = 0; i < ${#scripts[@]}; i = $((i + 2)) )); do
    echo $PROXY $DL -o ${scripts[$i]} ${scripts[$((i + 1))]}
    $PROXY $DL -o ${scripts[$i]} ${scripts[$((i + 1))]}
done

exit 0
